puts "Hello World!"
puts "Hello Again"
puts "I like typing this."
puts "This is fun."
puts "Yay! Printing."
puts "I'd must rather you 'not'."
puts 'I "said" do not touch this.'
puts "
Study Drills"
puts "Drill 1"
puts "Hello World!"
puts "Hello Again"
puts "I like typing this."
puts "This is fun."
puts "Yay! Printing."
puts "I'd must rather you 'not'."
puts 'I "said" do not touch this.'
puts "I am adding an additional line."
puts "
Drill 2"
#puts "Hello World!"
#puts "Hello Again"
#puts "I like typing this."
#puts "This is fun."
puts "Yay! Printing."
#puts "I'd must rather you 'not'."
#puts 'I "said" do not touch this.'
puts "
Drill 3"
#puts "Hello World!"
#puts "Hello Again"
#puts "I like typing this."
#puts "This is fun."
#puts "Yay! Printing."
#puts "I'd must rather you 'not'."
#puts 'I "said" do not touch this.'
puts "The # allows you to comment out parts of your code or add notes."
