puts "How many laps do I need to swim for a good workout?"
puts "Well how long is the pool?"
puts "The pool is 50 m long"
puts "Okay and you are trying to swim 1600 m?"
puts "Yes and each lap is #{50*2} meters"
puts "Okay so you would just divide your total by the meters in one lap. You need to do #{1600/(50*2)} laps"
