mon = " little monkeys jumping on the bed, one fell off and bummped his head, mama called the doctor and the doctor said 'no more monkeys jummping on the bed!'"
last_mon = " little monkeys jumping on the bed, one fell off and bummped his head, mama called the doctor and the doctor said 'GET THOSE MONKEYS RIGHT TO BED!'"
p "10 #{mon}"
p "9 #{mon}"
p "8 #{mon}"
p "7 #{mon}"
p "6 #{mon}"
p "5 #{mon}"
p "4 #{mon}"
p "3 #{mon}"
p "2 #{mon}"
p "1 #{last_mon}"
